---
language: node_js
node_js:
  - "5.11"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "npm config set spin false"

install:
  - npm install

#before_script:
  #- cp .env.example .env

script:
  - npm test

notifications:
  email: false
